apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jstmzlfeg-python
  janus-idp.io/tekton: jstmzlfeg-python
  backstage.io/kubernetes-id: jstmzlfeg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jstmzlfeg-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
